spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: asdf

  redis:
    host: redis
    port: 6379

  data:
    mongodb:
      uri: ${MONGO_URI}
      username:
      password:
      test:
        connectionString: ${MONGO_TEST_URI}

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 60000

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  id: ${ADMIN_MAIL_ID}
  password: ${ADMIN_MAIL_PW}
server:
  port: 8081

jasypt:
  encryptor:
    password: ${JASYPT_PW}
    bean: jasyptStringEncryptor
    algorithm: ${JASYPT_ALGO}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

kafka:
  sharing:
    topic: ${SHARING_TOPIC}
    groupId: ${SHARING_GROUP_ID}
    broker: ${SHARING_BROKER}

  aggregation:
    topic: ${AGGREGATION_TOPIC}
    groupId: ${AGGREGATION_GROUP_ID}
    broker: ${AGGREGATION_BROKER}

firebase:
  sdk:
    path: tteolione-firebase-adminsdk-fk0ms-ed40ba5d01.json

kakao:
  admin: ${KAKAO_ADMIN_KEY}

apple:
  grant-type: ${APPLE_GRANT_TYPE}
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  team-id: ${APPLE_TEAM_ID}
  audience: ${APPLE_AUDIENCE}
  private-key: ${APPLE_PRIVATE_KEY}
  apple-auth:
    url: ${APPLE_AUTH_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true